Attempt to correct workflow

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -11,8 +11,38 @@ permissions:
   id-token: write # Required for OIDC authentication
 
 jobs:
+  check-codeql:
+    name: Check CodeQL Analysis
+    runs-on: ubuntu-24.04
+    # Continue workflow even if this job fails due to inability to find and/or check CodeQL workflow
+    continue-on-error: true
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4.2.2
+
+      - name: Set up GitHub CLI
+        run: sudo apt-get install gh
+
+      - name: Authenticate GitHub CLI
+        env:
+          GH_PAT: ${{ secrets.GH_PAT }}
+        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
+
+      - name: Check CodeQL Workflow
+        env:
+          GH_PAT: ${{ secrets.GH_PAT }}
+        run: |
+          gh run list --workflow "CodeQL" --json conclusion --jq '.[0].conclusion' > codeql_status.txt
+          CODEQL_STATUS=$(cat codeql_status.txt)
+          if [[ "$CODEQL_STATUS" != "success" ]]; then
+            echo "CodeQL Analysis did not succeed. Exiting..."
+            exit 1
+          fi
+          rm codeql_status.txt
+
   build:
     name: Build Site
+    needs: check-codeql
     runs-on: ubuntu-24.04
 
     steps:
@@ -40,10 +70,15 @@ jobs:
 
   deploy:
     name: Deploy to GitHub Pages
-    needs: build
+    needs: [check-codeql, build]
     runs-on: ubuntu-24.04
 
     steps:
+      - name: Set up Git user
+        run: |
+          git config --global user.email "github@sl.neteng.cc"
+          git config --global user.name "SunDevil311"
+
       - name: Download Build Artifact
         uses: actions/download-artifact@v4.3.0
         with:
@@ -52,5 +87,5 @@ jobs:
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4.0.0
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          github_token: ${{ secrets.GH_PAT }}
           publish_dir: ./build # Replace this with the actual build output directory
